user_input = input("Enter String value : ")
print("Output : ", user_input.upper())
print("Output : ", user_input.lower())
print("Output : ", user_input.capitalize())
print("Output : ", user_input.count)
print("Output : ", user_input.split(","))
print("Output : ", user_input.splitlines())